# Generated by Django 3.2.16 on 2024-08-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы убрать из корзины.', verbose_name='В корзине'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_favorited',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы убрать из избранного.', verbose_name='В избранном'),
        ),
    ]
