# Generated by Django 3.2.16 on 2024-08-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240828_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='recipe',
        ),
        migrations.AddField(
            model_name='cart',
            name='recipe',
            field=models.ManyToManyField(to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
