# Generated by Django 3.2.16 on 2024-08-29 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20240828_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор избранного')),
                ('recipe', models.ManyToManyField(to='recipes.Recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'Список подписок',
            },
        ),
    ]
