# Generated by Django 3.2.16 on 2024-09-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_description_recipe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
