# Generated by Django 3.2.16 on 2024-08-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240829_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'избранное', 'verbose_name_plural': 'Список избранных рецептов'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='recipe',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
