# Generated by Django 3.2.16 on 2024-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240830_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
