# Generated by Django 3.2.16 on 2024-08-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_cart_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
